### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by xiaya** [gaowanli/PinGo#2]
新下载的运行会崩溃TopicInfo.swift第57行

**Comment by arden** [comment]
一运行就报错了。

**Comment by zcpdog** [comment]
+1

**Comment by zcpdog** [comment]
2016-02-05 10:13:42.902 PinGo[99964:4926755] -[**NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000003
2016-02-05 10:13:42.915 PinGo[99964:4926755] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000003'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010de30e65 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010fd98deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010de3948d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x000000010dd8690a ___forwarding_** + 970
    4   CoreFoundation                      0x000000010dd864b8 _CF_forwarding_prep_0 + 120
    5   libswiftCore.dylib                  0x00000001103502f3 _TTSf4g_d___TFSSCfMSSFT12_cocoaStringPSs9AnyObject__SS + 131
    6   libswiftCore.dylib                  0x00000001103179c3 _TFSSCfMSSFT12_cocoaStringPSs9AnyObject__SS + 19
    7   libswiftFoundation.dylib            0x00000001106e0260 _TF10Foundation24_convertNSStringToStringFGSqCSo8NSString_SS + 16
    8   PinGo                               0x000000010d9a105a _TToFC5PinGo9TopicInfos6beautyGSqSS_ + 74
    9   Foundation                          0x000000010e4219bb -[NSObject(NSKeyValueCoding) setValue:forKey:] + 288
    10  PinGo                               0x000000010d9a20ec _TFC5PinGo9TopicInfocfMS0_FT4dictGSqGVSs10DictionarySSPSs9AnyObject____S0_ + 3724
    11  PinGo                               0x000000010d9a2308 _TFC5PinGo9TopicInfoCfMS0_FT4dictGSqGVSs10DictionarySSPSs9AnyObject____S0_ + 88
    12  PinGo                               0x000000010d9a49c6 _TFZFC5PinGo9TopicInfo18fetchTopicInfoListFMS0_FTSb5orderSi9sortValueSS10completionFT5isEndSb9sortValueSS13topicInfoListGSqGSaS0____T__T_U_FGSqCS_15NetworkResponse_T_ + 1542
    13  PinGo                               0x000000010d9b4c9c _TFZFC5PinGo11NetworkTool11requestJSONFMS0_FTO9Alamofire6Method9URLStringSS10parametersGSqGVSs10DictionarySSPSs9AnyObject___10completionFT8responseGSqCS_15NetworkResponse__T__T_U_FGVS1_8ResponsePS4__CSo7NSError_T_ + 492
    14  Alamofire                           0x000000010db515c7 _TTRXFo_oGV9Alamofire8ResponsePSs9AnyObject_CSo7NSError__dT__XFo_iGS0_PS1__S2___dT__ + 71
    15  Alamofire                           0x000000010db4f90e _TFFFC9Alamofire7Request8responseuRq_S_22ResponseSerializerType_FS0_FT5queueGSqPSo17OS_dispatch_queue__18responseSerializerq_17completionHandlerFGVS_8Responseqq_S1_16SerializedObjectqq_S1_11ErrorObject_T__DS0_U_FT_T_U_FT_T_ + 1486
    16  Alamofire                           0x000000010db4e726 _TPA__TFFFC9Alamofire7Request8responseuRq_S_22ResponseSerializerType_FS0_FT5queueGSqPSo17OS_dispatch_queue__18responseSerializerq_17completionHandlerFGVS_8Responseqq_S1_16SerializedObjectqq_S1_11ErrorObject_T__DS0_U_FT_T_U_FT_T_ + 214
    17  Alamofire                           0x000000010db167d7 _TTRXFo__dT__XFdCb__dT__ + 39
    18  libdispatch.dylib                   0x0000000111598e5d _dispatch_call_block_and_release + 12
    19  libdispatch.dylib                   0x00000001115b949b _dispatch_client_callout + 8
    20  libdispatch.dylib                   0x00000001115a12af _dispatch_main_queue_callback_4CF + 1738
    21  CoreFoundation                      0x000000010dd90d09 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    22  CoreFoundation                      0x000000010dd522c9 __CFRunLoopRun + 2073
    23  CoreFoundation                      0x000000010dd51828 CFRunLoopRunSpecific + 488
    24  GraphicsServices                    0x0000000114c9bad2 GSEventRunModal + 161
    25  UIKit                               0x000000010e875610 UIApplicationMain + 171
    26  PinGo                               0x000000010d986bad main + 109
    27  libdyld.dylib                       0x00000001115ed92d start + 1
    28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hulinSun** [comment]
-[NSCFNumber length]: unrecognized selector sent to instance 0xb000000000000003
